/*
 delegate (c) KNOWLEDGECODE | MIT
*/
'use strict';var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(c){return c.raw=c};$jscomp.createTemplateTagFirstArgWithRaw=function(c,f){c.raw=f;return c};$jscomp.arrayIteratorImpl=function(c){var f=0;return function(){return f<c.length?{done:!1,value:c[f++]}:{done:!0}}};$jscomp.arrayIterator=function(c){return{next:$jscomp.arrayIteratorImpl(c)}};
$jscomp.makeIterator=function(c){var f="undefined"!=typeof Symbol&&Symbol.iterator&&c[Symbol.iterator];return f?f.call(c):$jscomp.arrayIterator(c)};
(function(c,f){"object"===typeof exports&&"undefined"!==typeof module?module.exports=f():"function"===typeof define&&define.amd?define(f):(c="undefined"!==typeof globalThis?globalThis:c||self,c.delegate=f())})(this,function(){Element.prototype.matches||(Element.prototype.matches=Element.prototype.webkitMatchesSelector||Element.prototype.mozMatchesSelector||Element.prototype.msMatchesSelector);var c=new WeakMap,f=function(a,b){this.originalEvent=a;this.stop=!a.bubbles;this.abort=!1;this.currentTarget=
b};f.prototype.preventDefault=function(){this.originalEvent.preventDefault()};f.prototype.stopPropagation=function(){this.stop=!0};f.prototype.stopImmediatePropagation=function(){this.abort=this.stop=!0};var l=function(a){this._baseEventTarget=a;this._eventCache={};this._subscribers={}};l.prototype.listener=function(a,b){a=this._subscribers[b.type+a]||[];var d=b.currentTarget===window?window:b.target,e={};do{e.$jscomp$loop$prop$evt2$1=new f(b,d);a=a.filter(function(g){return function(h){return function(k){return g.$jscomp$loop$prop$evt2$1.abort?
!1:h===b.currentTarget?(k.selector||k.handler.call(h,g.$jscomp$loop$prop$evt2$1),!1):k.selector&&h.matches(k.selector)?(k.handler.call(h,g.$jscomp$loop$prop$evt2$1),!1):!0}}}(e)(d));if(!a.length||e.$jscomp$loop$prop$evt2$1.stop)break;e={$jscomp$loop$prop$evt2$1:e.$jscomp$loop$prop$evt2$1}}while(d=d.parentNode)};l.prototype.on=function(a,b,d){"function"===typeof b&&(d=b,b=null);var e=this._subscribers[a]=this._subscribers[a]||[];if(!e.some(function(k){return k.selector===b&&k.handler===d})&&(e.push({selector:b,
handler:d}),!this._eventCache[a])){var g=$jscomp.makeIterator(a.split(":"));e=g.next().value;g=g.next().value;var h=this.listener.bind(this,"passive"===g?":passive":"");this._eventCache[a]=h;this._baseEventTarget.addEventListener(e,h,{capture:!0,passive:"passive"===g})}return this};l.prototype.off=function(a,b,d){"function"===typeof b&&(d=b,b=null);a?b||d?(this._subscribers[a]=(this._subscribers[a]||[]).filter(function(e){return e.selector!==b||d&&e.handler!==d}),this._subscribers[a].length||delete this._subscribers[a]):
delete this._subscribers[a]:this._subscribers={};return this};l.prototype.one=function(a,b,d){var e=this,g=function(h){e.off(a,b||g,g);d.call(this,h)};return"function"===typeof b?(d=b,b=null,this.on(a,g)):this.on(a,b,g)};l.prototype.clear=function(){var a=this;this.off();Object.keys(this._eventCache).forEach(function(b){var d=$jscomp.makeIterator(b.split(":")),e=d.next().value;d=d.next().value;a._baseEventTarget.removeEventListener(e,a._eventCache[b],{capture:!0,passive:"passive"===d})});this._eventCache=
{};c.delete(this._baseEventTarget)};return function(a){if("function"!==typeof a.addEventListener)throw new TypeError(a+" is not an EventTarget");var b;(b=c.get(a))||(b=new l(a),c.set(a,b));return b}});
